apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica  
spec:
  replicas: 3
  selector:
    matchLabels:
      project: my-project
      ver: 0.1
  template:
    metadata:
      name: my-second-pod
      labels:
        project:  my-project
        ver: 0.1
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80

        