apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: my-nginx
  template:
  metadata:
    name: my-third-pod
    labels:
      app: my-nginx
  spec:
    containers:
    - name: my-nginx-container
      image: nginx
      ports:
      - containerPort: 80